Improve cmd line

diff --git a/release/sntd b/release/sntd
--- a/release/sntd
+++ b/release/sntd
@@ -6,27 +6,8 @@
 #  /___/_/  /_/ |_\___/___(_)___/_//_/
 #  version: 1.3.0 | https://space.sh
 #
-# Node: /run/
-# Run the Simplenetes Daemon to manage pods for all users
-# This target is meant to be run from the init system (systemd or other) to manage the pod life cycles of all users pods.
-# The user should be root.
-# The daemon will figure out where to find pods by looking in each users $HOME/.simplenetes-daemon.conf.
-# If a user changes the .simplenetes-daemon.conf then the daemon needs to be restarted for the change to take effect.
-# For each user having such a config the daemon will spawn a specific process managing the pods for that user.
-# It's responsibilities are:
-# 1) Check each Pod's state file to see what state it should have and invoke the pod script to make sure it has that state.
-#    The daemon will also create any ramdisks for the pod (if the daemon is run as root).
-# 2) Detect changes in pods config directories and invoke the pod script to signal the containers mounting those configs.
-# 3) Generate proxy configurations:
-#     i) Probe each Pod which has the state "running" for any clusterPorts.
-#     ii) For each running Pod with clusterPorts run the Readiness probe.
-#     iii) For each ready Pod generate the config.
-#     iiii) If aggregated config was changed, SIGHUP the hostproxy.
-# 4) Run the Liveness probe on each pod which has the state "running".
-# Note:
-#     There is a way of running this Daemon as a foreground process for a single user by adding a directory of the hosthome as argument to the daemon.
-#     This is a special behaviour and is only meant to be used in dev mode.
-# 
+# Node: /cmdline/
+# Use sntd as a standalone cmd line tool
 
 set -u  # Will not allow for unset variables being used.
 
@@ -35,6 +16,68 @@ SPACE_LOG_ENABLE_COLORS="${SPACE_LOG_ENABLE_COLORS:-1}"
 SPACE_ASSERT_EXIT="${SPACE_ASSERT_EXIT:-0}"
 SPACE_MUTE_EXIT="${SPACE_MUTE_EXIT:-0}"
 SPACE_MUTE_EXIT_MESSAGE="${SPACE_MUTE_EXIT_MESSAGE:-1}"
+SNTD_CMDLINE()
+{
+    local _SPACE_NAME="SNTD_CMDLINE"
+
+    local _out_rest=""
+    local _out_h="false"
+    local _out_V="false"
+    local _out_p="true"
+
+    local _out_f=""
+    local _out_o=""
+    local _out_d=""
+
+    if ! _GETOPTS "h V" "f o d p" 0 1 "$@"; then
+        printf "Usage: sntd [podname] [-f infile] [-o outfile] [-d srcdir] [-p true|false]\\n" >&2
+        return 1
+    fi
+
+    if [ "${_out_h}" = "true" ]; then
+        USAGE
+        return
+    fi
+
+    if [ "${_out_V}" = "true" ]; then
+        VERSION
+        return
+    fi
+
+    DAEMON_MAIN "${_out_rest}"
+}
+
+USAGE()
+{
+    local _SPACE_NAME="USAGE"
+    printf "%s\\n" "Usage:
+
+    sntd -h
+        Output this help
+
+    sntd -V
+        Output version
+
+    sntd [hosthome]
+
+        hosthome (optional)
+            Path to directory of the cluster root directory.
+            If provided the program will run pods only for that cluster project,
+            if the process is run as root then ramdisks will be available.
+
+            If the hosthome argument is left out then the process must be run as root and it
+            will then search for cluster directories for all users and manage the lifecycles
+            for all the cluster projects on the host.
+
+" >&2
+}
+
+VERSION()
+{
+    local _SPACE_NAME="VERSION"
+    printf "%s\\n" "Simplenetes daemon version 0.1."
+}
+
 DAEMON_MAIN()
 {
     local _SPACE_NAME="DAEMON_MAIN"
@@ -46,7 +89,7 @@ DAEMON_MAIN()
     # If not root and no dir given then exit.
     if [ $(id -u) != 0 ]; then
         if [ -z "${hostHome}" ]; then
-            _LOG "The daemon has to be run as root, unless it is meant to be run for a single user then provide the HOSTHOME dir as first argument" "fatal"
+            _LOG "The daemon has to be run as root, unless it is meant to be run for a single cluster project then provide the HOSTHOME dir as first argument" "fatal"
             return 1
         fi
     fi
@@ -90,27 +133,21 @@ DAEMON_MAIN()
 
     _LOG "Running as a system daemon for all users. PID: $$" "info"
 
-    local usersDone=""
+    local clustersDone=""
 
     while [ "${_EXIT}" -eq 0 ]; do
-        local dir=
-        for dir in /home/*; do
-            if [ ! -d "${dir}" ]; then
+        local file=
+        for file in $(find /home -mindepth 3 -maxdepth 3 -type f -name cluster-id.txt); do
+            local hostHome="${file%/*}"
+            if [ ! -d "${hostHome}/pods" ]; then
                 continue
             fi
-            local file="${dir}/.simplenetes-daemon.conf"
-            if [ ! -f "${file}" ]; then
+            # Check if we already have this cluster.
+            if STRING_ITEM_INDEXOF "${clustersDone}" "${hostHome}"; then
                 continue
             fi
 
-            # Check if we already have this user.
-            if STRING_ITEM_INDEXOF "${usersDone}" "${dir}"; then
-                continue
-            fi
-            usersDone="${usersDone}${usersDone:+ }${dir}"
-
-            local hostHome="$(cat "${file}")"
-            hostHome="$(FILE_REALPATH "${hostHome}")"
+            clustersDone="${clustersDone}${clustersDone:+ }${hostHome}"
             _LOG "Adding watch to ${hostHome}" "info"
 
             local pid=
@@ -118,11 +155,86 @@ DAEMON_MAIN()
             pid=$!
             main_pids="${main_pids}${main_pids:+ }${pid}"
         done
-        sleep 1
+        sleep 3
     done
 
     # Wait for sub processes to exit
     wait ${main_pids} 2>/dev/null >&2
+}
+
+_GETOPTS()
+{
+    local _SPACE_NAME="_GETOPTS"
+
+    local simpleSwitches="${1}"
+    shift
+
+    local richSwitches="${1}"
+    shift
+
+    local minPositional="${1:-0}"
+    shift
+
+    local maxPositional="${1:-0}"
+    shift
+
+    _out_rest=""
+
+    local options=""
+    local option=
+    for option in ${richSwitches}; do
+        options="${options}${option}:"
+    done
+
+    local posCount="0"
+    while [ "$#" -gt 0 ]; do
+        local flag="${1#-}"
+        if [ "${flag}" = "${1}" ]; then
+            # Non switch
+            posCount="$((posCount+1))"
+            if [ "${posCount}" -gt "${maxPositional}" ]; then
+                PRINT "Too many positional argumets, max ${maxPositional}" "error" 0
+                return 1
+            fi
+            _out_rest="${_out_rest}${_out_rest:+ }${1}"
+            shift
+            continue
+        fi
+        local flag2=
+        STRING_SUBSTR "${flag}" 0 1 "flag2"
+        if STRING_ITEM_INDEXOF "${simpleSwitches}" "${flag2}"; then
+            if [ "${#flag}" -gt 1 ]; then
+                PRINT "Invalid option: -${flag}" "error" 0
+                return 1
+            fi
+            eval "_out_${flag}=\"true\""
+            shift
+            continue
+        fi
+
+        local OPTIND=1
+        getopts ":${options}" "flag"
+        case "${flag}" in
+            \?)
+                PRINT "Unknown option ${1-}" "error" 0
+                return 1
+                ;;
+            :)
+                PRINT "Option -${OPTARG-} requires an argument" "error" 0
+                return 1
+                ;;
+            *)
+                STRING_ESCAPE "OPTARG"
+                eval "_out_${flag}=\"${OPTARG}\""
+                ;;
+        esac
+        shift $((OPTIND-1))
+    done
+
+    if [ "${posCount}" -lt "${minPositional}" ]; then
+        PRINT "Too few positional argumets, min ${minPositional}" "error" 0
+        return 1
+    fi
 }
 
 _LOG()
@@ -215,11 +327,11 @@ _TRAP_TERM_MAIN()
 
     trap - TERM INT
 
-    _LOG "Kill off all daemon processes: ${main_pids}" "info"
 
     local pid=
     for pid in ${main_pids}; do
-        kill -s HUP "${pid}" 2>/dev/null
+        _LOG "Kill off daemon process: ${pid}" "info"
+        kill -s HUP "${pid}"
     done
 
     # This will trigger the loop to end.
@@ -261,6 +373,9 @@ FILE_REALPATH()
     local _SPACE_NAME="FILE_REALPATH"
 
     local file="${1}"
+    shift
+
+    local pwd="${1:-$PWD}"
 
     if [ "${file#/}" != "${file}" ]; then
         # Already absolute
@@ -268,7 +383,7 @@ FILE_REALPATH()
         :
     else
         # Prepend the current directory.
-        file="${PWD}/${file}"
+        file="${pwd}/${file}"
     fi
 
     # Remove dots and act on double dots.
@@ -367,6 +482,101 @@ PRINT()
     else
         printf "%s%s%s\n" "${header}" "${_SPACE_NAME}" "${1}" >&2
     fi
+}
+
+STRING_SUBSTR()
+{
+    local _SPACE_NAME="STRING_SUBSTR"
+
+    # shellcheck disable=SC2034
+    local __sopriv="${1}"
+    shift
+
+    local __index="${1}"
+    shift
+
+    local __length="${1}"
+    shift
+
+    local __outvar="${1:-}"
+    shift $(( $# > 0 ? 1 : 0 ))
+
+    local __strlength="${#__sopriv}"
+
+    if [ "${__index}" -lt 0 ]; then
+        __index=$((__strlength+__index))
+    fi
+
+    if [ "${__index}" -ge 0 ]; then
+        if [ "${__length}" = "" ]; then
+            __length=$((__strlength-__index))
+        fi
+
+        if [ "${__length}" -lt 0 ]; then
+            __length=$((__strlength-__index+__length))
+        fi
+
+        if [ "$((__index+__length))" -le "${#__sopriv}" ]; then
+            local __wildcard=
+            STRING_REPEAT "?" "${__index}" "" "__wildcard"
+            local __substr="${__sopriv#${__wildcard}}"
+            STRING_REPEAT "?" "$((${#__substr}-__length))" "" "__wildcard"
+            __substr="${__substr%${__wildcard}}"
+            if [ -n "${__outvar}" ]; then
+                eval "${__outvar}=\"\${__substr}\""
+            else
+                printf "%s\\n" "${__outvar}"
+            fi
+            return 0
+        fi
+
+    fi
+
+    if [ -n "${__outvar}" ]; then
+        eval "${__outvar}=\"\""
+    fi
+}
+
+STRING_INDEXOF()
+{
+    local _SPACE_NAME="STRING_INDEXOF"
+
+    local substr="${1}"
+    shift
+
+    local string="${1}"
+    shift
+
+    local varname="${1-}"
+    shift $(( $# > 0 ? 1 : 0 ))
+
+    local rest="${string%%${substr}*}"
+
+    if [ "${rest}" = "${string}" ]; then
+        if [ -n "${varname}" ]; then
+            eval "${varname}=\"-1\""
+        fi
+        return 1
+    fi
+
+    if [ -n "${varname}" ]; then
+        eval "${varname}=\"${#rest}\""
+    fi
+    return 0
+}
+
+STRING_ESCAPE()
+{
+    local _SPACE_NAME="STRING_ESCAPE"
+
+    local ___char=
+    for ___char in \" \$ \( \) \< \> \| \& \/; do
+        case "${2-\"\$}" in
+            *${___char}*)
+                _STRING_ESCAPE "${1}" "${___char}"
+                ;;
+        esac
+    done
 }
 
 STRING_HASH()
@@ -536,6 +746,71 @@ STRING_ITEM_GET()
         fi
         __count=$((__count+1))
     done
+}
+
+STRING_REPEAT()
+{
+    local _SPACE_NAME="STRING_REPEAT"
+
+    local __string="${1}"
+    shift
+
+    local __count="${1}"
+    shift
+
+    local __separator="${1}"
+    shift
+
+    local __outvar="${1}"
+    shift
+
+    local __repeatedstring=""
+    while [ "${__count}" -gt 0 ]; do
+        __count=$((__count-1))
+        __repeatedstring="${__repeatedstring}${__string}"
+        if [ "${__count}" -gt 0 ]; then
+            __repeatedstring="${__repeatedstring}${__separator}"
+        fi
+    done
+
+    eval "${__outvar}=\"\${__repeatedstring}\""
+}
+
+_STRING_ESCAPE()
+{
+    local _SPACE_NAME="_STRING_ESCAPE"
+    local __right=
+    local __result=""
+    eval "__right=\$${1}"
+    local __left=
+    while true; do
+        # Cut from right up until last occurrence of char.
+        __left="${__right%%${2}*}"
+        if [ "${__left}" = "${__right}" ]; then
+            # Done
+            __result="${__result}${__left}"
+            break
+        fi
+        __right="${__right#$__left}"
+        # This seems to be necessary the remove the escapes properly.
+        __right="${__right#*${2}}"
+        # Now cut away from right all escapes, one by one..
+        local __escapes=""
+        local __left2=
+        while true; do
+            __left2="${__left%[\\]}"
+            if [ "${__left2}" = "${__left}" ]; then
+                # No more escapes
+                break
+            fi
+            # Escape encountered
+            __escapes="${__escapes}\\"
+            __left="${__left2}"
+        done
+        # Double the number of escapes and add one.
+        __result="${__result}${__left}${__escapes}${__escapes}\\${2}"
+    done
+    eval "${1}=\${__result}"
 }
 
 _FETCH_POD_FILES()
@@ -795,7 +1070,7 @@ _SPAWN_PROCESS()
     local pid=
     (
         local error=
-        # If running as root we will drop privileges here.
+        # If running as root we will drop privileges here, thanks to ${exec}.
         if ! error="$(SPACE_LOG_LEVEL="${_SUBPROCESS_LOG_LEVEL}" ${exec} "${podFile} ${command}" 2>&1)"; then
             _LOG "Could not exec ${podFile} ${command}. Error: ${error}" "error" "exec:${podFile}:${command}"
         else
@@ -864,14 +1139,14 @@ _CREATE_RAMDISK()
 
 main()
 {
-    DAEMON_MAIN "$@"
+    SNTD_CMDLINE "$@"
 
     # Space will print exit status.
     local _status=$?
     if [ "${_status}" -ne "${SPACE_ASSERT_EXIT}" ]; then
         if [ "${SPACE_MUTE_EXIT_MESSAGE}" != "1" ] && [ "${SPACE_LOG_LEVEL}" -ge 1 ]; then
             [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ -t 2 ] && printf "\033[31m" >&2
-            printf "%s\n" "[ERROR] Script exited with status $_status for node /run/" >&2
+            printf "%s\n" "[ERROR] Script exited with status $_status for node /cmdline/" >&2
             [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ -t 2 ] && printf "\033[0m" >&2
         fi
         if [ "${SPACE_MUTE_EXIT}" != 1 ]; then
@@ -879,7 +1154,7 @@ main()
         fi
     elif [ "${SPACE_MUTE_EXIT_MESSAGE}" != "1" ] && [ "${SPACE_LOG_LEVEL}" -ge 5 ]; then
         [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ 5 -eq 3 ] && [ -t 2 ] && printf "\033[32m" >&2
-        printf "%s\n" "[DEBUG] Script exited with success (status $_status) for node /run/" >&2
+        printf "%s\n" "[DEBUG] Script exited with success (status $_status) for node /cmdline/" >&2
         [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ 5 -eq 3 ] && [ -t 2 ] && printf "\033[0m" >&2
         : # Important to reset status here.
     fi
