Fix bug and add -o switch

diff --git a/release/sntd b/release/sntd
--- a/release/sntd
+++ b/release/sntd
@@ -23,14 +23,11 @@ SNTD_CMDLINE()
     local _out_rest=""
     local _out_h="false"
     local _out_V="false"
-    local _out_p="true"
 
-    local _out_f=""
     local _out_o=""
-    local _out_d=""
 
-    if ! _GETOPTS "h V" "f o d p" 0 1 "$@"; then
-        printf "Usage: sntd [podname] [-f infile] [-o outfile] [-d srcdir] [-p true|false]\\n" >&2
+    if ! _GETOPTS "h V" "o" 0 1 "$@"; then
+        printf "Usage: sntd [clusterHome]  [-o logfile] \\n" >&2
         return 1
     fi
 
@@ -44,7 +41,13 @@ SNTD_CMDLINE()
         return
     fi
 
-    DAEMON_MAIN "${_out_rest}"
+    local logfile="${_out_o}"
+
+    if [ -n "${logfile}" ]; then
+        DAEMON_MAIN "${_out_rest}" 2>>"${logfile}"
+    else
+        DAEMON_MAIN "${_out_rest}"
+    fi
 }
 
 USAGE()
@@ -58,7 +61,7 @@ USAGE()
     sntd -V
         Output version
 
-    sntd [hosthome]
+    sntd [hosthome] [-o logfile]
 
         hosthome (optional)
             Path to directory of the cluster root directory.
@@ -68,6 +71,11 @@ USAGE()
             If the hosthome argument is left out then the process must be run as root and it
             will then search for cluster directories for all users and manage the lifecycles
             for all the cluster projects on the host.
+
+        -o logfile
+            Path to logfile to append output.
+            In left out then output to stderr.
+
 
 " >&2
 }
@@ -301,7 +309,7 @@ _DAEMON_RUN()
     local _STARTTS="$(date +%s)"
     local _CURRENT_STATES=""
 
-    # Global:
+    # Global in this process:
     _PHASE="normal"
 
     trap _TRAP_TERM HUP
@@ -641,9 +649,9 @@ _DAEMON_ITERATE()
         return 1
     fi
 
-    # Wait at least 10 seconds before updating the proxy.conf since it may flicker to empty otherwise on startup.
+    # Initially wait at least 10 seconds before updating the proxy.conf since it may flicker to empty otherwise on startup.
     local ts="$(date +%s)"
-    if [ "$((ts-_STARTTS >10000))" -eq 1 ]; then
+    if [ $((ts-_STARTTS >10)) ]; then
         if ! _WRITE_PROXY_CONFIG; then
             _LOG "Could not write proxy config" "error"
             return 1
@@ -943,8 +951,13 @@ _SPAWN_PROCESSES()
         local stateChanged="false"
         if _SPAWN_STATE_CHANGED "${nakedFile}" "${state}"; then
             stateChanged="true"
-            _LOG "State changed, exec ${nakedFile} ${state}" "info" 0
+            _LOG "State changed. Exec ${nakedFile} ${state}" "info" 0
             _LOG_CLEAR "exec:${nakedFile}"
+        fi
+
+        if [ -n "${changedConfigs}" ]; then
+            _LOG "Configs changed. Reload configs for ${nakedFile} ${state}" "info" 0
+            _LOG_CLEAR "config:${nakedFile}"
         fi
 
         if [ "${stateChanged}" = "true" ] ||
@@ -1055,9 +1068,9 @@ _SPAWN_PROCESS()
                     local error=
                     if ! error="$(_CREATE_RAMDISK "${podDir}" "${name}" "${size}" 2>&1)"; then
                         _LOG "Could not create ramdisk ${name}:${size} in ${podDir}, Error: ${error}" "error" "ramdisk:${podDir}:${name}:${size}"
+                        return 1
                     else
                         _LOG "Created ramdisk ${name}:${size} in ${podDir}" "info" "ramdisk:${podDir}:${name}:${size}"
-                        return 1
                     fi
                 done
             fi
@@ -1067,7 +1080,7 @@ _SPAWN_PROCESS()
     elif [ "${state}" = "removed" ]; then
         command="rm"
     else
-        LOG "State file has unknown state." "debug"
+        _LOG "State file has unknown state." "debug"
         return 0
     fi
 
@@ -1087,9 +1100,7 @@ _SPAWN_PROCESS()
         fi
         if [ -n "${changedConfigs}" ]; then
             if ! error="$(SPACE_LOG_LEVEL="${_SUBPROCESS_LOG_LEVEL}" ${exec} "${podFile} reload-configs ${changedConfigs}" 2>&1)"; then
-                _LOG "Could not exec ${podFile} reload-configs. Error: ${error}" "error" 0
-            else
-                _LOG "Exec ${podFile} reload-configs" "info" 0
+                _LOG "Could not exec ${podFile} reload-configs. Error: ${error}" "error" "config:${podFile}"
             fi
         fi
 
